# Generated by Django 4.2.3 on 2023-07-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0002_tag_alter_author_description_alter_quote_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='quote',
        ),
    ]
